# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:android)

platform :android do
    desc "Build and upload Android APK to Firebase"
        package = load_json(json_path: "./package.json")            
        lane :build_and_upload_apk do
            latest_release = firebase_app_distribution_get_latest_release(
                  app: ENV['FIREBASE_APP_ID'],
                  firebase_cli_token: ENV['FIREBASE_CLI_TOKEN']
               )
        next_build_number = latest_release[:buildVersion].to_i + 1 
        increment_version_code(
                gradle_file_path: "./android/app/build.gradle",
                version_code: next_build_number
                )
        increment_version_name(
                gradle_file_path: "./android/app/build.gradle",
                version_name: ENV['APK_VERSION_NAME']
                )
    gradle(task: "clean", project_dir: "android")
    gradle(
        task: "assemble", 
        build_type: "Release", 
        project_dir: "android")

    release = firebase_app_distribution(
        app: ENV['FIREBASE_APP_ID'],
        firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
        release_notes: ENV['RELEASE_NOTES'],
        groups: ENV['TESTERS_GROUP'],
        android_artifact_type: "APK",
        android_artifact_path: "android/app/build/outputs/apk/release/app-release.apk")
  end
end

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    pilot( api_key_path: "fastlane/82545M9GLY.json" )   
    increment_build_number(xcodeproj: "./ios/plateaumed.xcodeproj")
    build_app(workspace: "./ios/plateaumed.xcworkspace", scheme: "plateaumed")
    upload_to_testflight
  end
end 
