enum frontDeskRouteNames {
  FD_ROOT_NAVIGATION = 'FD_ROOT_NAVIGATION',
  FD_BOTTOM_TAB = 'FD_BOTTOM_TAB',
  FD_APPOINTMENTS = 'FD_APPOINTMENTS',
  FD_CREATE_INVOICE = 'FD_CREATE_INVOICE',
  FD_PAY_INVOICE = 'FD_PAY_INVOICE',
  FD_CALENDAR = 'FD_CALENDAR',
  FD_MESSAGES = 'FD_MESSAGES',
  FD_NOTIFICATIONS = 'FD_NOTIFICATIONS',
  FD_PROFILE = 'FD_PROFILE',
  FD_ADD_NEW_PATIENT = 'FD_ADD_NEW_PATIENT',
  FD_ADD_NEW_APPOINTMENT = 'FD_ADD_NEW_APPOINTMENT',
  FD_EDIT_APPOINTMENT = 'FD_EDIT_APPOINTMENT',
  FD_VIEW_APPOINTMENT_INFO = 'FD_VIEW_APPOINTMENT_INFO',
  FD_SCAN_PAPER_RECORDS = 'FD_SCAN_PAPER_RECORDS',
  FD_PATIENT_PROFILE = 'FD_PATIENT_PROFILE',
  FD_PATIENT_OVERVIEW = 'FD_PATIENT_OVERVIEW',
  FD_REVIEW_DETAILED_HISTORY = 'FD_REVIEW_DETAILED_HISTORY',
  FD_PAYMENT_CONFIRMATION = 'FD_PAYMENT_CONFIRMATION',
  FD_WARD_ROUND_AND_CLINIC_NOTES = 'FD_WARD_ROUND_AND_CLINIC_NOTES',
  FD_VIEW_REFERRAL_LETTER = 'FD_VIEW_REFERRAL_LETTER',
  FD_ADD_DEMOGRAPHIC_INFO = 'FD_ADD_DEMOGRAPHIC_INFO',
}

enum doctorRouteNames {
  DOCTOR_ROOT_NAVIGATION = 'DOCTOR_ROOT_NAVIGATION',
  DOCTOR_BOTTOM_TAB = 'DOCTOR_BOTTOM_TAB',
  DOCTOR_PATIENTS = 'DOCTOR_PATIENTS',
  DOCTOR_ALL_PATIENTS = 'DOCTOR_ALL_PATIENTS',
  DOCTOR_MESSAGES = 'DOCTOR_MESSAGES',
  DOCTOR_NOTIFICATIONS = 'DOCTOR_NOTIFICATIONS',
  DOCTOR_ALL_INPUTS = 'DOCTOR_ALL_INPUTS',
  DOCTOR_DIAGNOSIS = 'DOCTOR_DIAGNOSIS',
  DOCTOR_PRESENTING_COMPLAINTS = 'DOCTOR_PRESENTING_COMPLAINTS',
  DOCTOR_PRESCRIPTIONS = 'DOCTOR_PRESCRIPTIONS',
  DOCTOR_PROCEDURES = 'DOCTOR_PROCEDURES',
}

enum nurseRouteNames {
  NURSE_ROOT_NAVIGATION = 'NURSE_ROOT_NAVIGATION',
  NURSE_BOTTOM_TAB = 'NURSE_BOTTOM_TAB',
  NURSE_PATIENTS = 'NURSE_PATIENTS',
  NURSE_AUTO_ASSIGN = 'NURSE_AUTO_ASSIGN',
  NURSE_MESSAGES = 'NURSE_MESSAGES',
  NURSE_NOTIFICATIONS = 'NURSE_NOTIFICATIONS',
  NURSE_PROFILE = 'NURSE_PROFILE',
  NURSING_CARE_PLAN = 'NURSING_CARE_PLAN',
  NURSE_MISCELLANEOUS_INTERVENTIONS = 'NURSE_MISCELLANEOUS_INTERVENTIONS',
  NURSE_BED_MAKING = 'NURSE_BED_MAKING',
  NURSE_WOUND_DRESSING = 'NURSE_WOUND_DRESSING',
  NURSE_INTAKE_OUTPUT_CHARTING = 'NURSE_INTAKE_OUTPUT_CHARTING',
  OUT_PATIENT_NURSE_ALL_INPUT_LANDING_DASHBOARD = 'OUT_PATIENT_NURSE_ALL_INPUT_LANDING_DASHBOARD',
  IN_PATIENT_NURSE_ALL_INPUT_LANDING_DASHBOARD = 'IN_PATIENT_NURSE_ALL_INPUT_LANDING_DASHBOARD',
}

type RouteNames = {
  AUTH_STACK: 'AUTH_STACK';
  LOGIN: 'LOGIN';
  RESET_PASSWORD: 'RESET_PASSWORD';
  ENTER_OTP: 'ENTER_OTP';
  CREATE_NEW_PASSWORD: 'CREATE_NEW_PASSWORD';
  FRONT_DESK: typeof frontDeskRouteNames;
  DOCTOR: typeof doctorRouteNames;
  NURSE: typeof nurseRouteNames;
  VIEW_PARER_RECORDS_TAB: 'VIEW_PARER_RECORDS_TAB';

  ADD_NOTES: 'ADD_NOTES';
  VITAL_SIGNS: 'VITAL_SIGNS';
  INVESTIGATIONS: 'INVESTIGATIONS';

  OTHER_PLAN_ITEMS: 'OTHER_PLAN_ITEMS';
};

export const routesNames: RouteNames = {
  AUTH_STACK: 'AUTH_STACK',
  LOGIN: 'LOGIN',
  RESET_PASSWORD: 'RESET_PASSWORD',
  ENTER_OTP: 'ENTER_OTP',
  CREATE_NEW_PASSWORD: 'CREATE_NEW_PASSWORD',
  FRONT_DESK: frontDeskRouteNames,
  DOCTOR: doctorRouteNames,
  NURSE: nurseRouteNames,
  VIEW_PARER_RECORDS_TAB: 'VIEW_PARER_RECORDS_TAB',
  ADD_NOTES: 'ADD_NOTES',
  VITAL_SIGNS: 'VITAL_SIGNS',
  INVESTIGATIONS: 'INVESTIGATIONS',
  OTHER_PLAN_ITEMS: 'OTHER_PLAN_ITEMS',
};
