name: 'Setup'
description: 'Setup Nodejs and install Dependencies'

runs:
  using: 'composite'
  steps:
    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18   
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'        
    - name: Install dependencies
      shell: bash
      run: |
          npm install -g yarn
          yarn install
          gem install fastlane -NV
