name: "Manual Test APK Build"

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to'
        required: true
        type: choice
        default: 'Firebase App Distribution'
        options:
          - 'Firebase App Distribution'    
      releaseNotes:
        description: 'Release Notes'
        required: false
      versionNamePrefix:
        description: 'Version Name Prefix'
        required: false
        default: 'Test Build APK'
        type: string
      versionCode:
        description: 'Build Number'
        required: false
        default: ''
        type: string


jobs:
   buildUatApk:
    name: Build APK
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # - name: Setup
      #   uses: ./.github/workflows/actions/setup

      # - name: Install plugins
      #   run: |
      #     cd ios
      #     bundle install
      #     pod install

      - name: Run Fastlane Deployment
        run: |
          gem install fastlane
          fastlane beta
         
